Mittagessen.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mittagessen.Data.Entities;
using Mittagessen.Data.Interfaces;
using Mittagessen.Web.Helpers;
using Mittagessen.Web.Models;
using StructureMap.Attributes;
using System.Threading;

namespace Mittagessen.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        [SetterProperty]
        public ILunchRepository LunchRepository { get; set; }

        [SetterProperty]
        public IUserRepository UserRepository { get; set; }

        [SetterProperty]
        public IMealRepository MealRepository { get; set; }

        [SetterProperty]
        public IEnrollmentRepository EnrollmentRepository { get; set; }

        public ActionResult Index()
        {
            var thisWeekLunches = LunchRepository.GetLunchesForThisWeek().ToList();
            var user = UserRepository.GetUserByName(User.Identity.Name);
            if (user == null)
                return RedirectToAction("LogOff", "Account");
            var model = new EnrollmentModel()
                            {
                                MyLunches = new HashSet<Guid>(user.Enrollments.Select(e => e.EnrolledForLunchId)),
                                Lunches = thisWeekLunches
                            };

            var userRatings = MealRepository.GetUserRatings(user.Id);
            var meals = MealRepository.GetAll();
            var ratingModel = new RatingModel()
            {
                Meals = meals,
                UserRatings = userRatings.ToDictionary(m => m.RatedMealId, m => m.Rating)
            };
            model.RatingModel = ratingModel;

            return View(model);
        }

        public ActionResult InfoPage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult EnrollUser(Guid lunchId, Guid? variation = null)
        {
            var user = UserRepository.GetUserByName(User.Identity.Name);
            var enrollment = new Enrollment()
            {
                EnrolledById = user.Id,
                EnrolledForLunchId = lunchId,
                EnrollmentDate = DateTime.Now,
                MealVariationId = variation
            };
            var success = EnrollmentRepository.TryInsert(enrollment);
            var lunch = LunchRepository.Get(lunchId);
            UpdateLunchInfoOnClients(lunch);

            return Json(new
            {
                userEnrolled = success,
                numberOfEnrollments = lunch.NumberOfEnrollments,
                numberOfPortions = lunch.NumberOfPortions
            });
        }

        [HttpPost]
        public ActionResult DisenrollUser(Guid lunchId)
        {
            var user = UserRepository.GetUserByName(User.Identity.Name);
            var enrollment = EnrollmentRepository.Get(user.Id, lunchId);
            var success = EnrollmentRepository.TryDelete(enrollment);
            var lunch = LunchRepository.Get(lunchId);
            UpdateLunchInfoOnClients(lunch);

            return Json(new
            {
                userEnrolled = !success,
                numberOfEnrollments = lunch.NumberOfEnrollments,
                numberOfPortions = lunch.NumberOfPortions
            });
        }

        [NonAction]
        private void UpdateLunchInfoOnClients(Lunch lunch)
        {
            var hub = Microsoft.AspNet.SignalR.GlobalHost.ConnectionManager.GetHubContext<Hubs.EnrollmentHub>();
            hub.Clients.All.lunchInfoUpdated(lunch.Id, lunch.NumberOfEnrollments, lunch.NumberOfPortions);
        }
    }
}

Mittagessen.Web/Controllers/OverviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StructureMap.Attributes;
using Mittagessen.Data.Interfaces;
using Mittagessen.Data.Entities;
using Mittagessen.Web.Helpers;
using Mittagessen.Web.Models;

namespace Mittagessen.Web.Controllers
{
    [Authorize]
    public class OverviewController : Controller
    {
        [SetterProperty]
        public IMealRepository MealRepository { get; set; }

        [SetterProperty]
        public IUserRepository UserRepository { get; set; }

        [HttpGet]
        public ActionResult Meals()
        {
            var user = UserRepository.GetUserByName(User.Identity.Name);
            var userRatings = MealRepository.GetUserRatings(user.Id);
            var meals = MealRepository.GetAll();
            var ratingModel = new RatingModel()
            {
                Meals = meals,
                UserRatings = userRatings.ToDictionary(m => m.RatedMealId, m => m.Rating)
            };
            return View(ratingModel);
        }

        [HttpGet]
        public ActionResult MealDetails(Guid mealId)
        {
            var meal = MealRepository.Get(mealId);
            return View(meal);
        }

        [HttpPost]
        public JsonResult RateMeal(Guid mealId, double value)
        {
            var user = UserRepository.GetUserByName(User.Identity.Name);
            MealRepository.RateMeal(user.Id, mealId, value);
            var meal = MealRepository.Get(mealId);
            return Json(new { rating = meal.AverageRatingRounded });
        }
    }
}

Mittagessen.Web/Views/Home/EnrollButton.cshtml
@model Mittagessen.Data.Entities.Lunch

@{
    Layout = null;
}

<input lunch-id="@Model.Id" type='button' value='Abmelden' class='btn btn-danger disenroll-button' data-bind="visible: userEnrolled, disable: changingEnrollment, click: disenrollForLunch" />

<span class="badge badge-info" data-bind="visible: showIsFull"><div class='termin-full-msg'>Termin voll</div></span>

<input lunch-id="@Model.Id" type='button' value='Anmelden' class='btn btn-primary enroll-button' data-bind="visible: canEnroll, disable: changingEnrollment, click: enrollForLunch" />

Mittagessen.Web/Views/Home/Index.cshtml
@model Mittagessen.Web.Models.EnrollmentModel
           
@{
    ViewBag.Title = "Mittagessen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    //Lunch enrollment view model
    var EnrollmentViewModel = function (lunchId, userEnrolled, numberOfPortions, numberOfEnrollments, rating) {
        this.lunchId = lunchId;
        this.userEnrolled = ko.observable(userEnrolled);
        this.numberOfPortions = ko.observable(numberOfPortions);
        this.numberOfEnrollments = ko.observable(numberOfEnrollments);
        this.changingEnrollment = ko.observable(false);
        this.showIsFull = ko.computed(function () {
            return this.userEnrolled() == false && parseInt(this.numberOfEnrollments()) >= parseInt(this.numberOfPortions());
        }, this);
        this.canEnroll = ko.computed(function () {
            return this.showIsFull() == false && this.userEnrolled() == false;
        }, this);
        this.enrollForLunch = function () {
            this.changingEnrollment(true);
            enrollUser(this.lunchId);
        };
        this.disenrollForLunch = function () {
            this.changingEnrollment(true);
            disenrollUser(this.lunchId);
        };
        this.mealRating = ko.observable(rating);
    };

    //All local view models
    var ViewModels = new Array();

    //Initialization
    $(function () {
        //Initialize enrollments view models
        $(".lunch-info").each(function () {
            //Set up the view model parameters
            lunchId = $(this).attr("lunch-id");
            userEnrolled = $(this).find(".user-enrolled-msg").is(":visible");
            numberOfPortions = $(this).find(".number-of-portions-info").text();
            numberOfEnrollments = $(this).find(".number-of-enrollments-info").text();
            rating = $(this).find(".rating-info").text();
            
            //Add the view model
            var vm = new EnrollmentViewModel(lunchId, userEnrolled, numberOfPortions, numberOfEnrollments, rating);
            ViewModels[lunchId] = vm;
            ko.applyBindings(vm, this);
        });

        $(".rateit").bind('rated', rateMeal);

        $.connection.enrollmentHub.client.lunchInfoUpdated = updateLunchInfo;
        $.connection.hub.start();
    });

    function enrollUser(lunchId) {
        var variationRadioName = "meal-variation-" + lunchId;
        var variation = $("input:radio[name=" + variationRadioName + "]:checked").val();
        $.post('@Url.Action("EnrollUser")', { lunchId: lunchId, variation: variation }, function (result) {
            updateLunch(lunchId, result.userEnrolled, result.numberOfEnrollments, result.numberOfPortions);
        });
    }

    function disenrollUser(lunchId) {
        $.post('@Url.Action("DisenrollUser")', { lunchId: lunchId }, function (result) {
            updateLunch(lunchId, result.userEnrolled, result.numberOfEnrollments, result.numberOfPortions);
        });
    }

    function updateLunch(lunchId, userEnrolled, enrollments, portions) {
        ViewModels[lunchId].userEnrolled(userEnrolled);
        updateLunchInfo(lunchId, enrollments, portions);

        ViewModels[lunchId].changingEnrollment(false);        
    }

    function updateLunchInfo(lunchId, enrollments, portions) {
        ViewModels[lunchId].numberOfPortions(portions);
        ViewModels[lunchId].numberOfEnrollments(enrollments);
    }

    function rateMeal(event, value) {
        parentContainer = $(this).parents('.lunch-info').last();
        mealId = parentContainer.attr('meal-id');
        lunchId = parentContainer.attr('lunch-id');
        $.post('@Url.Action("RateMeal", "Overview")', { mealId: mealId, value: value }, function (data) {
            ViewModels[lunchId].mealRating(data.rating);
        });
    }
</script>

<h2>Anmeldung</h2>

<div style="font-size:18px;font-family:Georgia;text-align:justify;margin-right:10px" class="alert alert-danger">
    Die Mittagessen werden nach dem <b>4. September 2014</b> nur gelegentlich stattfinden!
</div>

@foreach (var lunch in Model.Lunches)
{    
    <div class="meal lunch-info" lunch-id="@lunch.Id" meal-id="@lunch.CookedMealId">
        <div>
            <div>
                <h5 style="float:left">@lunch.LunchDate.ToShortDateString() @lunch.LunchDate.ToShortTimeString()</h5>
                <span class="label label-success user-enrolled-msg" data-bind="visible: userEnrolled" @(Model.EnrolledByUser(lunch) ? null : "style=display:none")>Angemeldet</span>
            </div>

            <div class="meal-img">
                <img alt="@lunch.CookedMeal.Name" src="@lunch.CookedMeal.ImageName"  />
            </div>
            <div class="meal-name">
                <h4>@lunch.CookedMeal.Name</h4>
            </div>
            <div>
                <a href="#modal-@lunch.Id" role="button" class="btn" style="float: right" data-toggle="modal">Optionen</a>
            </div>

            <div class="meal-footer">
                <table>
                    <tr>
                        <td><span style='font-family:Verdana; font-weight:bolder'>Mahlzeiten:</span></td>
                        <td><span class="badge badge-info number-of-portions-info" data-bind="text: numberOfPortions">@lunch.NumberOfPortions</span></td>
                    </tr>
                    <tr>
                        <td><span style='font-family:Verdana; font-weight:bolder'>Angemeldet:</span></td>
                        <td><span class="badge badge-success number-of-enrollments-info" data-bind="text: numberOfEnrollments">@lunch.NumberOfEnrollments</span></td>
                    </tr>
                </table>
                <div style="margin-left:auto;margin-right:auto;margin-top:10px;width:7em">

                    @if (Model.IsAfterDeadline(lunch))
                    {
                        <span class="badge badge-warning"><div class='termin-past-msg'>Termin vergangen</div></span>
                    }
                    else
                    {
                        @Html.Partial("EnrollButton", lunch)
                    }
                </div>
                @if (Model.IsAfterDeadline(lunch) && Model.EnrolledByUser(lunch))
                {
                    <div class="meal-rating">
                        <div style="font-family: Georgia">Wie hat Ihnen die Mahlzeit geschmeckt?</div>
                        <div class="rateit" style="float:left" meal-id="@lunch.CookedMealId" 
                                data-rateit-resetable="false" data-rateit-value="@Model.RatingModel.UserRating(lunch.CookedMealId)" data-rateit-ispreset="true" 
                                data-rateit-step=1 data-rateit-max=10></div>
                    </div>
                }
            </div>

            <div class="modal hide fade in" id="modal-@lunch.Id" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
                 style="width: 700px">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel">@lunch.CookedMeal.Name</h3>
              </div>
              <div class="modal-body">                
                <div style="float: right; width:250px">
                    <h3>Variationen</h3>
                    <div data-bind="visible: canEnroll">                        
                        @Html.RadioButton("meal-variation-" + @lunch.Id, "", true)
                        <span>Mit Allem</span>
                        <br />
                        @if (lunch.CookedMeal.Variations.Count == 0)
                        {
                            <div class="alert alert-info">
                                Es gibt zurzeit keine Variationen für diesen Gericht
                            </div>
                        }
                        @foreach (var variation in lunch.CookedMeal.Variations)
                        {
                            <span title="@(variation.RequiresDeadLine ? "Diese Variation kann nur spätestens 18 Stunden vor dem Mittagessen ausgewählt werden" : "")">
                                @Html.RadioButton("meal-variation-" + @lunch.Id,
                                    variation.Id,
                                    Model.VariationAfterDeadline(lunch, variation) ? new { disabled = "disabled" } : null)
                                <span style="@(Model.VariationAfterDeadline(lunch, variation) ? "color:grey" : "")">@variation.Name</span>
                            </span>
                            <br />
                        }
                    </div>
                    <div data-bind="visible: userEnrolled" class="alert alert-info">
                        Um eine andere Variation auszuwählen, melden Sie sich bitte zuerst ab
                    </div>
                </div>
                <div style="width:400px">
                    <img alt="@lunch.CookedMeal.Name" src="@lunch.CookedMeal.ImageName"  />
                </div>
                <div>
                    <h4>@lunch.CookedMeal.Description</h4>
                </div>
              </div>
              <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>                
                @Html.Partial("EnrollButton", lunch)
              </div>
            </div>
        </div>
    </div>   
}

Mittagessen.Web/Views/Home/InfoPage.cshtml
@{
    ViewBag.Title = "InfoPage";
}

<h2>Infoseite</h2>

<div style="font-size:larger; text-align:justify; margin-right:10px">
    <div>
        <p>Liebe Gäste,</p>
        <p>
            wir danken Ihnen, dass Sie sich bei uns registriert haben. Mit unserem Mitagessen-Service bieten wir Ihnen frisches gesundes Essen für einen günstigen Preis an.
            <b>Eine Mahlzeit kostet 4 Euro</b>, enthält meistens Salat und eine ausreichende Menge an Nahrung.
            Wir versuchen hier die wichtigsten Fragen zu beantworten. Falls Sie noch eine Frage haben, schreiben Sie uns bitte an die E-Mail-Adresse <b>dusan.dudo@gmail.com</b>.
        </p>
    </div>
    <div>
        <h3>Was sollte mich motivieren zu kommen</h3>
        <p>            
            Die Nahrungsmitteln werden meistens am vorrigen Tag gekauft und die Mahlzeiten werden immer frisch vorbereitet. 
            Innerhalb der Woche versuchen wir eine ausgewogene Menge vom Fleisch und Gemüse anzubieten. 
        </p>
        <p>
            Viele Mahlzeiten sind vegetarisch, oder haben eine vegetarische Variation.
            Durch die verschiedene Variationen können Sie oft Ihre Mahlzeit Ihren eigenen Wünschen anpassen.
        </p>
        <p>
            Fragen Sie Ihre Kollegen, die uns schon besucht haben, oder kommen Sie einfach vorbei und probieren Sie unseren Service selbst aus.
        </p>
    </div>
    <div>
        <h3>Wo und wann finden die Mittagessen statt:</h3>
        <p>        
            Sie finden uns <b>in der Küche im Erdgeschoss</b>. Gehen Sie einfach in die Tür neben der Bank im Hof und dann in die Tür auf der linken Seite.            
        </p>
        <p>
            Das Mittagessen findet um <b>12:30</b> immer am <b>Dienstag</b>, <b>Mittwoch</b> und <b>Donnerstag</b> statt.
        </p>
    </div>
    <div>
        <h3>Wie kann ich mich anmelden:</h3>
        <p>
            Die Anmeldung ist auf der Homepage möglich. Sehen Sie sich einfach die Mahlzeiten an und melden Sie sich mit dem Knopf <i>Anmelden</i>.
            Mit dem Knopf <i>Optionen</i> können Sie sich die Zutaten anschauen oder eine bestimmte Variation auswählen.
        </p>
    </div>
    <div>
        <h3>Wie kann ich für die Mittagessen zahlen:</h3>
        <p>
            Sie können an der Rezeption beim Empfang die Mittagessen-Chips kaufen und diese dann für die Mahlzeiten austauschen. 
            Falls Sie aber unseren Service nur ausprobieren möchten, können Sie Ihren ersten Chip auch bei uns direkt kaufen.
        </p>
    </div>
    <div>
        <h3>Was sollte ich noch wissen:</h3>
        <h5>Die Mahlzeit mitnehmen</h5>
        <p>
            Die Mahlzeit können Sie mit den anderen Gästen direkt in der Küche essen, oder mitnehmen. Im zweiten Fall hilft uns sehr wenn Sie einen sauberen Teller mitbringen. 
        </p>
        <h5>E-Mail-Benachrichtigung</h5>
        <p>
            Am Anfang der Woche erhalten Sie von uns an Ihre E-Mail-Adresse eine E-Mail mit Fotos und kurzen Beschreibungen der aktuellen Mahlzeiten.
        </p>
        <h5>Mahlzeit-Bewertung</h5>
        <p>
            Kurz nach dem Mittageseen können Sie die Mahlzeit direkt auf der Homepage bewerten.
        </p>
    </div>
</div>