Mittagessen.Web/Areas/Sprava/Controllers/LunchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mittagessen.Data.Entities;
using Mittagessen.Web.Areas.Sprava.Models;
using Mittagessen.Web.Helpers;
using Mittagessen.Web.Infrastructure;
using StructureMap.Attributes;
using Mittagessen.Data.Interfaces;

namespace Mittagessen.Web.Areas.Sprava.Controllers
{
    [Authorize(Roles = "admin")]
    public class LunchController : Controller
    {
        [SetterProperty]
        public IMealRepository MealRepository { get; set; }

        [SetterProperty]
        public ILunchRepository LunchRepository { get; set; }

        public ActionResult Index()
        {
            var lunches = LunchRepository.GetAll();

            return View(lunches);
        }

        [HttpGet]
        public ActionResult Create(Guid? mealId = null)
        {           
            var lunchModel = new LunchModel()
            {
                LunchDate = LunchRepository.NextLunchDate(),
                LunchTime = TimeSpan.FromHours(12) + TimeSpan.FromMinutes(30),
                NumberOfPortions = 10
            };

            if (mealId.HasValue)
            {
                var meal = MealRepository.Get(mealId.Value);
                lunchModel.CookedMealId = meal.Id;
                lunchModel.CookedMealName = meal.Name;
            }

            return View(lunchModel);
        }

        [HttpGet]
        [ChildActionOnly]
        public ActionResult CreatePartial()
        {
            var lunchModel = new LunchModel()
            {
                LunchDate = LunchRepository.NextLunchDate(),
                LunchTime = TimeSpan.FromHours(12) + TimeSpan.FromMinutes(30),
                NumberOfPortions = 10
            };
            return View(lunchModel);
        }

        [HttpPost]
        public ActionResult Create(LunchModel lunchModel)
        {
            if (ModelState.IsValid)
            {
                var lunch = new Lunch();
                Mapper.Map(lunchModel, lunch);
                LunchRepository.Insert(lunch);

                return RedirectToAction("Index");
            }
            else
            {
                return View(lunchModel);
            }
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var lunch = LunchRepository.Get(id);
            var lunchModel = Mapper.Map(lunch, new LunchModel());

            return View(lunchModel);
        }

        [HttpPost]
        public ActionResult Edit(LunchModel lunchModel)
        {
            if (ModelState.IsValid)
            {
                var lunch = LunchRepository.Get(lunchModel.LunchId);
                Mapper.Map(lunchModel, lunch);
                LunchRepository.Update(lunch);

                UpdateLunchInfoOnClients(lunch);

                return RedirectToAction("Index");
            }
            else
            {
                return View(lunchModel);
            }
        }

        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            var lunch = LunchRepository.Get(id);
            LunchRepository.Delete(lunch);
            return RedirectToAction("Index");
        }

        public ActionResult MealList()
        {
            var meals = MealRepository.GetAll();
            return View(meals);
        }

        [NonAction]
        private void UpdateLunchInfoOnClients(Lunch lunch)
        {
            var hub = Microsoft.AspNet.SignalR.GlobalHost.ConnectionManager.GetHubContext<Hubs.EnrollmentHub>();
            hub.Clients.All.lunchInfoUpdated(lunch.Id, lunch.NumberOfEnrollments, lunch.NumberOfPortions);
        }
    }
}

Mittagessen.Web/Areas/Sprava/Controllers/MealController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StructureMap.Attributes;
using Mittagessen.Data.Interfaces;
using Mittagessen.Data.Entities;
using System.IO;
using System.Configuration;
using Mittagessen.Web.Helpers;
using System.ComponentModel.DataAnnotations;

namespace Mittagessen.Web.Areas.Sprava.Controllers
{
    [Authorize(Roles="admin")]
    public class MealController : Controller
    {
        [SetterProperty]
        public IMealRepository MealRepository { get; set; }

        public ActionResult Index()
        {
            var meals = MealRepository.GetAll();
            return View(meals);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new Meal());
        }

        [HttpPost]
        public ActionResult Create(Meal meal, [Required] HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                SaveMealImage(meal, file);

                MealRepository.Insert(meal);
                return RedirectToAction("Index");
            }
            else
            {
                return View(meal);
            }
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var meal = MealRepository.Get(id);
            return View(meal);
        }

        [HttpPost]
        public ActionResult Edit(Meal meal, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                SaveMealImage(meal, file);
                MealRepository.Update(meal);
                return RedirectToAction("Index");
            }
            else
            {
                return View(meal);
            }
        }

        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            var meal = MealRepository.Get(id);
            DeleteExistingImage(meal);
            MealRepository.Delete(meal);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult AddVariation(Guid mealId)
        {
            var variation = new MealVariation()
            {
                MealId = mealId
            };
            return View(variation);
        }

        [HttpPost]
        public ActionResult AddVariation(MealVariation variation)
        {
            MealRepository.AddVariation(variation.MealId, variation.Name, variation.RequiresDeadLine);

            return RedirectToAction("Edit", new { id = variation.MealId });
        }

        [HttpGet]
        public ActionResult RemoveVariation(Guid mealId, Guid variationId)
        {
            MealRepository.RemoveVariation(variationId);
            return RedirectToAction("Edit", new { id = mealId });
        }

        [HttpPost]
        public void UpdateVariation(Guid variationId, bool requiresDeadline)
        {
            MealRepository.UpdateVariation(variationId, requiresDeadline);
        }

        private void SaveMealImage(Meal meal, HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                DeleteExistingImage(meal);

                var fileName = Guid.NewGuid().ToString().Replace('-', '_') + ".jpg";

                meal.ImageName = this.Url.Content("~" + ConfigurationManager.AppSettings["UploadsPath"] + "/" + fileName);

                var path = Path.Combine(Server.MapPath("~" + meal.ImageName));
                file.SaveAs(path);                
            }
        }

        private void DeleteExistingImage(Meal meal)
        {
            if (!string.IsNullOrEmpty(meal.ImageName))
            {
                var oldImgPath = Server.MapPath("~" + meal.ImageName);
                if (System.IO.File.Exists(oldImgPath))
                    System.IO.File.Delete(oldImgPath);
            }
        }
    }
}

Mittagessen.Web/Areas/Sprava/Views/Meal/AddVariation.cshtml
@model Mittagessen.Data.Entities.MealVariation

@{
    ViewBag.Title = "AddVariation";
    Layout = null;
}

<h3>Variacie</h3>

@using (Html.BeginForm("AddVariation", "Meal", FormMethod.Post))
{
    @Html.HiddenFor(x => x.MealId)
    <div>
        @Html.LabelFor(x => x.Name)
        @Html.TextBoxFor(x => x.Name)
    </div>
    
    <input type="submit" class="btn btn-primary" value="Pridat" />
}

Mittagessen.Web/Areas/Sprava/Views/Meal/Create.cshtml
@model Mittagessen.Data.Entities.Meal

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div>
        @using(Html.BeginForm("Create", "Meal", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(m => m.Id)
        
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name, new { style="width:400px" })
            @Html.ValidationMessageFor(m => m.Name)
        
            @Html.LabelFor(m => m.Description)
            @Html.TextAreaFor(m => m.Description, new { style = "width:400px;height:200px" })
            @Html.ValidationMessageFor(m => m.Description)

            @Html.LabelFor(m => m.ImageName)
            @Html.EditorFor(m => m.ImageName)
            @Html.ValidationMessageFor(m => m.ImageName)

            <div>
                <input type="submit" class="btn btn-primary" style="width:150px;height:40px;margin-top:20px" value="Ulozit" />
            </div>
        }
    </div>

Mittagessen.Web/Areas/Sprava/Views/Meal/Edit.cshtml
@model Mittagessen.Data.Entities.Meal

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(function () {
        $("#variation-list input[type='checkbox']").change(function () {
            var variationId = $(this).parent("li").attr("variation-id");
            $.post('@Url.Action("UpdateVariation")', { variationId: variationId, requiresDeadline : $(this).is(":checked") });
        });
    });
</script>

<div class="span8">
    <div>
        @Html.ActionLink("Naplanovat obed", "Create", "Lunch", new { mealId = Model.Id }, new { @class="btn btn-primary" })
    </div>

    <div>
        @using(Html.BeginForm("Edit", "Meal", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(m => m.Id)
        
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name, new { style="width:400px" })
            @Html.ValidationMessageFor(m => m.Name)
        
            @Html.LabelFor(m => m.Description)
            @Html.TextAreaFor(m => m.Description, new { style = "width:400px;height:200px" })
            @Html.ValidationMessageFor(m => m.Description)

            @Html.LabelFor(m => m.ImageName)
            @Html.EditorFor(m => m.ImageName)
            @Html.ValidationMessageFor(m => m.ImageName)

            <div>
                <input type="submit" class="btn btn-primary" style="width:150px;height:40px;margin-top:20px" value="Ulozit" />
            </div>
        }
    </div>
</div>

<div class="span3">
    <div>
        @Html.Action("AddVariation", new { mealId = Model.Id })
    </div>

    <div>
        <ul id="variation-list">
            @foreach (var variation in Model.Variations)
            {
                <li variation-id="@variation.Id">
                    @Html.CheckBoxFor(m => variation.RequiresDeadLine)
                    @variation.Name 
                    @Html.ActionLink("Zmazat", "RemoveVariation", new { mealId = Model.Id, variationId = variation.Id })
                </li>
            }
        </ul>
    </div>
</div>

Mittagessen.Web/Areas/Sprava/Views/Meal/Index.cshtml
@model IEnumerable<Mittagessen.Data.Entities.Meal>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    @Html.ActionLink("Novy recept", "Create", null, new { @class = "btn btn-primary" })
</div>

@foreach (var meal in Model)
{
    <div class="meal">
        <a href='@Url.Action("Edit", new { id = meal.Id })'>
            <div class="meal-img">
                <img alt="@meal.Name" src="@meal.ImageName" />
            </div>
            <div class="meal-name">
                <span>@meal.Name</span>
            </div>
        </a>
    </div>
}